services:
  db:
    image: postgres:15
    container_name: weather_db
    restart: always
    environment:
      POSTGRES_DB: weatherdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s

  app:
    build: .
    container_name: weather_app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

volumes:
  postgres_data: